server:
  port: 8080
  servlet:
    context-path:

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  redis:
    host: 127.0.0.1
    #    password: root
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
